solution/IPMRVPark/IPMRVPark.WebUI/Controllers/ReservationController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using IPMRVPark.Models;
using IPMRVPark.Contracts.Repositories;
using IPMRVPark.Services;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace IPMRVPark.WebUI.Controllers
{
    public class ReservationController : Controller
    {
        IRepositoryBase<customer_view> customers;
        IRepositoryBase<staff_view> users;
        IRepositoryBase<ipmevent> ipmevents;
        IRepositoryBase<session> sessions;
        IRepositoryBase<placeinmap> placesinmap;
        IRepositoryBase<selecteditem> selecteditems;
        IRepositoryBase<reservationitem> reservationitems;
        IRepositoryBase<payment> payments;
        IRepositoryBase<paymentreservationitem> paymentsreservationitems;
        IRepositoryBase<rvsite_available_view> rvsites_available;
        IRepositoryBase<site_description_rate_view> sites_description_rate;
        SessionService sessionService;
        PaymentService paymentService;

        public ReservationController(
            IRepositoryBase<customer_view> customers,
            IRepositoryBase<staff_view> users,
            IRepositoryBase<ipmevent> ipmevents,
            IRepositoryBase<placeinmap> placesinmap,
            IRepositoryBase<rvsite_available_view> rvsites_available,
            IRepositoryBase<selecteditem> selecteditems,
            IRepositoryBase<reservationitem> reservationitems,
            IRepositoryBase<payment> payments,
            IRepositoryBase<paymentreservationitem> paymentsreservationitems,
            IRepositoryBase<session> sessions,
            IRepositoryBase<site_description_rate_view> sites_description_rate
            )
        {
            this.customers = customers;
            this.users = users;
            this.ipmevents = ipmevents;
            this.payments = payments;
            this.paymentsreservationitems = paymentsreservationitems;
            this.placesinmap = placesinmap;
            this.selecteditems = selecteditems;
            this.reservationitems = reservationitems;
            this.rvsites_available = rvsites_available;
            this.sites_description_rate = sites_description_rate;
            this.sessions = sessions;
            sessionService = new SessionService(
                this.sessions,
                this.customers,
                this.users
                );
            paymentService = new PaymentService(
                this.selecteditems,
                this.reservationitems,
                this.payments,
                this.paymentsreservationitems
                );
        }//end Constructor

        #region Common

        const long newReservationMode = -1;
        const long IDnotFound = -1;

        // Convert dates in number of days counting from today
        private void CreateViewBagsForDates(long selectedID = newReservationMode)
        {
            session _session = sessionService.GetSession(this.HttpContext, false, false);
            ipmevent _IPMEvent = ipmevents.GetById(_session.idIPMEvent);

            // Read and convert the dates to a value than can be used by jQuery Datepicker
            DateTime start = _IPMEvent.startDate.Value;
            DateTime end = _IPMEvent.endDate.Value;
            DateTime now = DateTime.Now;
            DateTime checkInDate = DateTime.MinValue;
            DateTime checkOutDate = DateTime.MinValue.AddDays(1);

            // Parameters for Edit Reservation, NOT used for New Reservation
            if (selectedID != newReservationMode)
            {
                selecteditem _selecteditem = selecteditems.GetById(selectedID);
                checkInDate = _selecteditem.checkInDate;
                _session.checkInDate = checkInDate;
                checkOutDate = _selecteditem.checkOutDate;
                _session.checkOutDate = checkOutDate;
            }

            if (checkInDate == DateTime.MinValue)
            {
                if (_session.checkInDate != null)
                {
                    checkInDate = _session.checkInDate.Value;
                };
            };

            if (checkOutDate == DateTime.MinValue.AddDays(1))
            {
                if (_session.checkOutDate != null)
                {
                    checkOutDate = _session.checkOutDate.Value;
                };
            };

            if (!(checkInDate >= start && checkInDate <= end))
            {
                checkInDate = start;
            };

            if (!(checkOutDate >= checkInDate && checkOutDate <= end))
            {
                checkOutDate = end;
            };

            int min = (int)(start - now).TotalDays + 1;
            int max = (int)(end - now).TotalDays + 1;
            int checkIn = (int)(checkInDate - now).TotalDays;
            int checkOut = (int)(checkOutDate - now).TotalDays;

            ViewBag.minDate = min;
            ViewBag.maxDate = max;
            ViewBag.checkInDate = checkIn;
            ViewBag.checkOutDate = checkOut;
        }
        #endregion

        #region New Reservation - Site Selected

        // Partial View for CRUD of Selected Item 
        public ActionResult CRUDSelectedItem(long selectedID = newReservationMode)
        {
            ViewBag.UserID = sessionService.GetSessionUserID(this.HttpContext, true, false);
            CreateViewBagsForDates(selectedID);

            // Parameters for Edit Reservation, NOT used for New Reservation
            if (selectedID != newReservationMode)
            {
                selecteditem _selecteditem = selecteditems.GetById(selectedID);
                ViewBag.SelectedID = selectedID;
                ViewBag.SiteID = _selecteditem.idRVSite;
                placeinmap _placeinmap = placesinmap.GetById(_selecteditem.idRVSite);
                ViewBag.SiteName = _placeinmap.site;
            }
            else
            {
                ViewBag.SiteID = newReservationMode;
            }

            return PartialView();
        }

        // New Reservation Page - Site Selection
        public ActionResult NewReservation()
        {
            long userID = sessionService.GetSessionUserID(this.HttpContext, true, false);
            ViewBag.UserID = userID;
            // Clean items that are in selected table
            paymentService.CleanEditSelectedItems(
                sessionService.GetSessionID(this.HttpContext, false, false),
                userID
                );

            return View();
        }

        // Edit Selected Item
        public ActionResult EditSelected(long selectedID = newReservationMode)
        {
            ViewBag.SelectedID = selectedID;
            ViewBag.UserID = sessionService.GetSessionUserID(this.HttpContext, true, false);

            return View();
        }

        // Update session's check-in and check-out dates
        [HttpPost]
        public ActionResult SelectCheckInOutDates(DateTime checkInDate, DateTime checkOutDate)
        {
            var _session = sessionService.GetSession(this.HttpContext, true, false);
            _session.checkInDate = checkInDate;
            _session.checkOutDate = checkOutDate;
            sessions.Update(sessions.GetById(_session.ID));
            sessions.Commit();

            return Json(checkInDate);
        }

        // Select site button, add site to selected table
        [HttpPost]
        public ActionResult SelectSite(long idRVSite, DateTime checkInDate, DateTime checkOutDate)
        {
            var _session = sessionService.GetSession(this.HttpContext, true, false);

            // Check if site is really available
            bool isRVSiteAvailable = rvsites_available.GetAll().
                Where(s => s.idIPMEvent == _session.idIPMEvent && s.id == idRVSite).
                ToList().Count() > 0;

            if (isRVSiteAvailable)
            {
                // Check if site is already in the list (it was previously cancelled)
                // If it is, remove it
                var old_selecteditems = selecteditems.GetAll().Where(osi => osi.idRVSite == idRVSite).ToList();
                foreach (var old_selecteditem in old_selecteditems)
                {
                    //selecteditems.Delete(old_selecteditem.ID);
                    //selecteditems.Commit();
                };

                // Add selected item to the database
                var _selecteditem = new selecteditem();
                var type_rates = sites_description_rate.GetAll().
                    Where(s => s.id == idRVSite).FirstOrDefault();

                _selecteditem.checkInDate = checkInDate;
                _selecteditem.checkOutDate = checkOutDate;
                _selecteditem.weeklyRate = type_rates.weeklyRate.Value;
                _selecteditem.dailyRate = type_rates.dailyRate.Value;
                _selecteditem.idRVSite = idRVSite;
                _selecteditem.idSession = _session.ID;
                _selecteditem.idIPMEvent = _session.idIPMEvent;
                _selecteditem.idStaff = _session.idStaff;
                _selecteditem.idCustomer = _session.idCustomer;
                _selecteditem.site = type_rates.RVSite;
                _selecteditem.siteType = type_rates.description;
                _selecteditem.isSiteChecked = true;
                CalcSiteTotal calcResults = new CalcSiteTotal(
                    checkInDate,
                    checkOutDate,
                    type_rates.weeklyRate.Value,
                    type_rates.dailyRate.Value,
                    true);
                _selecteditem.duration = calcResults.duration;
                _selecteditem.weeks = calcResults.weeks;
                _selecteditem.days = calcResults.days;
                _selecteditem.amount = calcResults.amount;

solution/IPMRVPark/IPMRVPark.WebUI/Views/Reservation/CRUDReservedItem.cshtml
<script type="text/javascript">
    $(document).ready(function () {
        // Resolve root path
        var origin = window.location.origin;
        if (origin == 'http://www.alvm.com.br') {
            var root = 'http://www.alvm.com.br/ipmrvpark/';
        }
        else {
            var root = '../';
        }
        // ****** Preparation For Edit Reservation
        if(@ViewBag.SiteID != -1){
            $('#btnSelectSite').hide();
            $('#btnLargeDisplay').hide();
            $('#btnUpdateSite').show();
            $('#btnCancelSite').show();
            $('#btnRemoveSite').show();
            $('#idRVSite').val(@ViewBag.SiteID);
            $('#siteName').prop('disabled', true);
            setTimeout( function(){
                getSiteData();
            }, 5000);
        }
        else{
        }
        $('#btnUpdateSite').click(function(event){
            $('#waitMsg').show();// Show wait message
        });
        $('#btnCancelSite').click(function(event){
            $('#waitMsg').show();// Show wait message
        });
        // ***** Dates Selection
        $('#checkInDate').datepicker({
            dateFormat: 'D, dd M yy',
            minDate: @ViewBag.minDate,
            maxDate: @ViewBag.maxDate,
            showOtherMonths: true,
            selectOtherMonths: true,
            dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
            onSelect: function () {
                var dt2 = $('#checkOutDate');
                var startDate = $(this).datepicker('getDate');
                //add 7 days to selected date
                startDate.setDate(startDate.getDate() + 7);
                var minDate = $(this).datepicker('getDate');
                minDate.setDate(minDate.getDate() + 1);
                //minDate of dt2 datepicker = dt1 selected day
                dt2.datepicker('setDate', startDate);
                //sets dt2 maxDate
                dt2.datepicker('option', 'maxDate', @ViewBag.maxDate);
                //first day which can be selected in dt2 is selected date in dt1
                dt2.datepicker('option', 'minDate', minDate);
                //$('#checkOutDate').val(startDate);
                selectCheckInOutDates(); // Update session with dates
                getSiteData(); // Calculate total for selected site
            }
        });
        $('#checkInDate').datepicker('setDate', @ViewBag.checkInDate);
        $('#checkInDate').click(function(event){
            var dim = $(this).offset();
            $('#ui-datepicker-div').offset({
                top     :   dim.top - 0,
                left    :   dim.left - 0
            });
        });
        $('#checkOutDate').datepicker({
            dateFormat: 'D, dd M yy',
            minDate: @ViewBag.checkInDate + 1,
            maxDate: @ViewBag.maxDate,
            showOtherMonths: true,
            selectOtherMonths: true,
            dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
            onSelect: function () {
                selectCheckInOutDates(); // Update session with dates
                getSiteData(); // Calculate total for selected site
                $('#siteName').focus();
            }
        });
        $('#checkOutDate').datepicker('setDate', @ViewBag.checkOutDate);
        $('#checkOutDate').click(function(event){
            var dim = $(this).offset();
            $('#ui-datepicker-div').offset({
                top     :   dim.top - 0,
                left    :   dim.left - 0
            });
        });
        function selectCheckInOutDates() {
            var postpath = root + 'Reservation/SelectCheckInOutDates';
            var checkInDate = $('#checkInDate').val().toString('dd/mm/yy');
            var checkOutDate = $('#checkOutDate').val().toString('dd/mm/yy');
            $.ajax({
                url: postpath,
                type: 'POST',
                dataType: 'json',
                data: {
                    checkInDate: checkInDate, //Reading text box values using jQuery
                    checkOutDate: checkOutDate //Reading text box values using jQuery
                },
                success: function (result) {
                },
                error: function (result) {
                    alert('Error in SelectCheckInOutDates');
                }
            });
        };
        // ***** Site Search
        $('#siteName').click(function (){
            $('#siteName').val('');
            $('#siteTotal').text('');
            $('#btnSelectSite').prop('disabled', true);
        });
        $('#siteName').autocomplete({
            source: function (request, response) {
                var postpath = root + 'Search/SearchSiteByNameResult';
                $.ajax({
                    url: postpath,
                    type: 'POST',
                    dataType: 'json',
                    data: { query: request.term },
                    success: response
                });
            },
            minLength: 1, // require at least one character from the user
            select: function (event, ui) {
                $('#idRVSite').val(ui.item.ID); // name of form input field: CustomerID, ProductID
                $('#btnSelectSite').prop('disabled', false);
                $('#btnSelectSite').focus();
                //$('body').scrollTo('#btnSelectSite');
                getSiteData(); // Calculate total for selected site
            }
        });
        function getSiteData() {
            if($('#idRVSite').val().length > 0) {// Check if idRVSite is null
                var postpath = root + 'Reservation/GetSiteData';
                $.ajax({
                    url: postpath,
                    type: 'POST',
                    dataType: 'json',
                    data: { //Passing data
                        checkInDate: $('#checkInDate').val(), //Reading text box values using jQuery
                        checkOutDate: $('#checkOutDate').val(),
                        idRVSite: $('#idRVSite').val()
                    },
                    success: function(site){
                        $('#siteTotal').text(site.amount);
                        $('#siteType').text(site.type);
                        $('#siteDailyRate').text(site.dailyRate);
                        $('#siteWeeklyRate').text(site.weeklyRate);
                        $('#waitMsg').hide();// Show wait message
                    },
                    error: function () {
                        alert('Error in GetSiteData');}
                });
            };
        };
        // ***** Site Selection
        $('#btnSelectSite').prop('disabled', true);
        //function will be called on button click
        $('#btnSelectSite').click(function () {
            $('#waitMsg').show();// Show wait message
            var postpath = root + 'Reservation/SelectSite';
            $.ajax({
                url: postpath,
                type: 'POST',
                dataType: 'json',
                data: { //Passing data
                    checkInDate: $('#checkInDate').val(), //Reading text box values using jQuery
                    checkOutDate: $('#checkOutDate').val(),
                    idRVSite: $('#idRVSite').val()
                },
                success: function (result) {
                    $('#btnSelectSite').prop('disabled', true); // Disable select button
                    $('#siteName').val(''); // Reset site name
                    $('#siteTotal').text(''); // Reset site total
                    $('#waitMsg').hide();
                    $('#customerName').focus();
                    //$('body').scrollTo('#customerName');
                },
                error: function (result) {
                    alert('Error in SelectSite' + $('#idRVSite').val() );
                }
            });
        });
    });
</script>

<div class="container-fluid">
    <!-- RV Site Dates-->
    <div class="row">
        <div class="col-sm-3 col-xs-12 form-top-margin">
            <label>Check In Date</label>
        </div>
        <div class="col-sm-3 col-xs-12 form-top-margin">
            <input type="text" id="checkInDate" class="form-control" />
        </div>
        <div class="col-sm-3 col-xs-12 form-top-margin">
            <label>Check Out Date</label>
        </div>
        <div class="col-sm-3 col-xs-12 form-top-margin">
            <input type="text" id="checkOutDate" class="form-control" />
        </div>
    </div>
    <!-- RV Site Selection -->
    <div class="row form-top-margin">
        <div class="col-sm-2 col-xs-12 form-top-margin">
            <label>RV Site</label>
        </div>
        <div class="col-sm-4 col-xs-12 form-top-margin" data-toggle="tooltip" title="Search and selecte with autocomplete">
            <input type="text" class="form-control" id="siteName" placeholder="Type letter or number then select from the list" value="@ViewBag.SiteName" />
            <input class="text-box single-line" id="idRVSite" name="idRVSite" type="hidden" />
        </div>
        <div class="col-sm-2 col-xs-12 form-top-margin">
            <div id="siteTotal" type="text" class="form-control" style="text-align:right" disabled>$ 0.00</div>
        </div>
        <div class="col-sm-4 col-xs-12 form-top-margin">
            <button id="btnSelectSite" class="btn btn-block btn-default">
                <span class="col-xs-1 glyphicon glyphicon-ok"></span>
                <span class="col-xs-9">Select Site</span>
            </button>
            <!-- Update Selected Site Dates -->
            <a id="btnUpdateSite" style="display: none;" href="@Url.Action("UpdateReserved","Reservation", new { id=@ViewBag.SelectedID })" class="btn btn-block btn-default btn-mylink pagination-centered">
                <span class="glyphicon glyphicon-pencil"></span>
                <span>Update Dates</span>
            </a>
        </div>
    </div>
    <div class="row form-top-margin">
        <div class="col-sm-1 col-xs-12 form-top-margin">
            <label>Type</label>
        </div>
        <div class="col-sm-3 col-xs-12 form-top-margin">
            <div id="siteType" type="text" class="form-control" disabled></div>
        </div>
        <div class="col-sm-2 col-xs-12 form-top-margin">
            <label>Daily Rate</label>
        </div>
        <div class="col-sm-2 col-xs-12 form-top-margin">
            <div id="siteDailyRate" type="text" class="form-control" style="text-align:right" disabled></div>
        </div>
        <div class="col-sm-2 col-xs-12 form-top-margin">
            <label>Weekly Rate</label>
        </div>
        <div class="col-sm-2 col-xs-12 form-top-margin">
            <div id="siteWeeklyRate" type="text" class="form-control" style="text-align:right" disabled></div>
        </div>
    </div>
    <div id="btnCancelSite" class="row form-top-margin" style="display: none;">
        <div class="col-sm-4 col-sm-push-8 col-xs-12 form-top-margin">
            <a class="btn btn-block btn-default btn-mylink pagination-centered" href="@Url.Action("RemoveReserved","Reservation", new { id=@ViewBag.SelectedID })"><span class="glyphicon glyphicon-erase"></span>&nbsp; Cancel</a>
        </div>
    </div>
</div>

solution/IPMRVPark/IPMRVPark.WebUI/Views/Reservation/EditReservation.cshtml
@model IEnumerable<IPMRVPark.Models.selecteditem>

@{
    ViewBag.Title = "Site Reservation";
    ViewBag.PageTitle = "Edit Reservation";
}

@Html.ActionLink("Home", "Menu", "Reservation")
<span class="glyphicon glyphicon-chevron-right"></span>
Site Reservation
<span class="glyphicon glyphicon-chevron-right"></span>
@Html.ActionLink("Edit Reservation", "Reservation", "Reservation")


<script type="text/javascript">
    $(document).ready(function () {
        $("#waitMsg").hide();// Hide wait message
        $('.showWaitMsg').click(function () {
            $("#waitMsg").show();// Show wait message
        });
    });
</script>

<div class="container-fluid">
    <div class="row form-top-margin">
        <div class="col-sm-2 col-xs-12 form-top-margin">
            <label>Customer</label>
        </div>
        <div class="col-sm-6 col-xs-12 form-top-margin">
            <div>@ViewBag.Customer</div>
        </div>
    </div>

    <!-- List of selected sites -->
    <div class="row form-top-margin">
        <div class="col-xs-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Site</th>
                        <th>Type</th>
                        <th>Check In</th>
                        <th>Check Out</th>
                        <th style="text-align:right;">Total</th>
                        <th style="border-top:none">
                            <div class="dropdown pull-right">
                                <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown">
                                    Action
                                    <span class="collapsible"></span>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                    <li class="showWaitMsg"><a id="removeAllSelected" href="@Url.Action("RemoveAllReserved","Reservation")"><span class="glyphicon glyphicon-erase"></span>&nbsp; Cancel All</a></li>
                                </ul>
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.site)</td>
                            <td>@Html.DisplayFor(modelItem => item.siteType)</td>
                            <td>@item.reservationCheckInDate.ToString("ddd"), @item.reservationCheckInDate.ToString("dd") @item.reservationCheckInDate.ToString("MMM")</td>
                            <td>@item.reservationCheckOutDate.ToString("ddd"), @item.reservationCheckOutDate.ToString("dd") @item.reservationCheckOutDate.ToString("MMM")</td>
                            <td style="text-align:right;">@Html.DisplayFor(modelItem => item.reservationAmount)</td>
                            <td rowspan="2" style="border-top:none">
                                <div class="dropdown pull-right">
                                    <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown">
                                        Action
                                        <span class="collapsible"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right">
                                        @if (item.isSiteChecked)
                                        {
                                            <li>
                                                <a href="@Url.Action("EditReserved", "Reservation", new { selectedID = item.ID })">
                                                    <span class="glyphicon glyphicon-pencil"></span>&nbsp; Edit
                                                </a>
                                            </li>
                                            <li class="showWaitMsg"><a href="@Url.Action("RemoveReserved", "Reservation", new { id = item.ID })"><span class="glyphicon glyphicon-erase"></span>&nbsp; Cancel</a></li>
                                        }
                                        else
                                        {
                                            <li class="showWaitMsg"><a href="@Url.Action("ReinsertReserved", "Reservation", new { id = item.ID })"><span class="glyphicon glyphicon-plus"></span>&nbsp; Reinsert</a></li>
                                        }
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <!-- Show changed values if there are changes-->
                        if (item.reservationAmount != item.total && item.isSiteChecked)
                        {
                            <tr>
                                <td style="border-top:none; padding-top: 0;"></td>
                                <td style="border-top:none; padding-top: 0;">Changed to:</td>
                                <td style="border-top:none; padding-top: 0;">@item.checkInDate.ToString("ddd"), @item.checkInDate.ToString("dd") @item.checkInDate.ToString("MMM")</td>
                                <td style="border-top:none; padding-top: 0;">@item.checkOutDate.ToString("ddd"), @item.checkOutDate.ToString("dd") @item.checkOutDate.ToString("MMM")</td>
                                <td style="border-top:none; padding-top: 0; text-align:right;">@Html.DisplayFor(modelItem => item.total)</td>
                            </tr>
                        }
                        else
                        {
                            <tr></tr>
                        }
                        if (!item.isSiteChecked)
                        {
                            <tr>
                                <td style="border-top:none; padding-top: 0;"></td>
                                <td style="border-top:none; padding-top: 0;">Cancelled:</td>
                                <td colspan="3" style="border-top:none; padding-top: 0; text-align:right;">@Html.DisplayFor(modelItem => item.total)</td>
                                <td style="border-top:none; padding-top: 0;"></td>
                            </tr>
                        }
                        else
                        {
                            <tr></tr>
                        }
                    }
                    <tr>
                        <td>Primary Reservation Total</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td style="text-align:right;">@ViewBag.PrimaryTotal</td>
                        <td></td>
                    </tr>
                    <!-- There are changes-->
                    @if (ViewBag.PrimaryTotal != ViewBag.SelectionTotal)
                    {
                        <tr>
                            <td>New Reservation Total</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td style="text-align:right;">@ViewBag.SelectionTotal</td>
                            <td></td>
                        </tr>
                        if (ViewBag.CancellationFee != "0.00")
                        {
                            <tr>
                                <td colspan="4" style="text-align:right;">Cancellation Fee</td>
                                <td style="text-align:right;">@ViewBag.CancellationFee</td>
                                <td></td>
                            </tr>
                        }
                        if (ViewBag.dueAmount != "0.00")
                        {
                            <tr>
                                <td colspan="4" style="text-align:right;">Due Amount</td>
                                <td style="text-align:right;">@ViewBag.dueAmount</td>
                                <td></td>
                            </tr>
                        }
                        else
                        {
                            <tr>
                                <td colspan="4" style="text-align:right;">Refund Amount</td>
                                <td style="text-align:right;">@ViewBag.refundAmount</td>
                                <td></td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    @if (ViewBag.dueAmount != "0.00")
    {
    <!-- Proceed To Payment -->
        <div class="showWaitMsg">
            <div class="row form-top-margin">
                <div class="col-sm-4 col-sm-push-8 col-xs-12 form-top-margin" data-toggle="tooltip" title="Go To">
                    <a id="btnPayment" href="@Url.Action("PaymentOrRefund", "Payment")" class="btn btn-block btn-default btn-mylink pagination-centered">
                        <span class="glyphicon glyphicon-usd"></span>
                        <span>Payment</span>
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div>
            </div>
        </div>
    }
    @if (ViewBag.refundAmount != "0.00")
    {
    <!-- Proceed To Refund -->
        <div class="showWaitMsg">
            <div class="row form-top-margin">
                <div class="col-sm-4 col-sm-push-8 col-xs-12 form-top-margin" data-toggle="tooltip" title="Go To">
                    <a id="btnRefund" href="@Url.Action("PaymentOrRefund", "Payment")" class="btn btn-block btn-warning btn-mylink pagination-centered">
                        <span class="glyphicon glyphicon-usd"></span>
                        <span>Refund</span>
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div>
            </div>
        </div>
    }
</div>