solution/IPMRVPark/IPMRVPark.WebUI/Controllers/ProvinceViewController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using IPMRVPark.Models;
using IPMRVPark.Contracts.Repositories;
using System.Collections.Generic;

namespace IPMRVPark.WebUI.Controllers
{
    public class ProvinceViewController : Controller
    {
        IRepositoryBase<province_view> provinces_view;
        IRepositoryBase<provincecode> provincecodes;
        IRepositoryBase<countrycode> countrycodes;

        public ProvinceViewController(IRepositoryBase<province_view> provinces_view,
                IRepositoryBase<provincecode> provincecodes,
                IRepositoryBase<countrycode> countrycodes)
        {
            this.provinces_view = provinces_view;
            this.provincecodes = provincecodes;
            this.countrycodes = countrycodes;
        }//end Constructor

        // GET: list with filter
        public ActionResult Index(string searchString)
        {
            var province_view = provinces_view.GetAll().OrderBy(q => q.provinceName);

            if (!String.IsNullOrEmpty(searchString))
            {
                province_view = province_view.Where(s => s.provinceName.Contains(searchString)).OrderBy(r => r.provinceName);
            }

            return View(province_view);
        }

        // GET: /Details/5
        public ActionResult ProvinceDetails(string id)
        {
            province_view province_view = provinces_view.GetAll().
                Where(c => c.provinceCode == id).FirstOrDefault();
            //var province_view = provinces_view.GetById(id);
            if (province_view == null)
            {
                return HttpNotFound();
            }
            return View(province_view);
        }

        // GET: /Create
        public ActionResult CreateProvince()
        {
            //Dropdown list for country
            var country = countrycodes.GetAll();
            ViewBag.Country = country.OrderBy(q => q.name);

            var province_view = new province_view();
            return View(province_view);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProvince(province_view province_form_page)
        {
            var _province = new provincecode();
            _province.code = province_form_page.provinceCode;
            _province.name = province_form_page.provinceName;
            _province.countryCode = province_form_page.countryCode;
            _province.createDate = DateTime.Now;
            _province.lastUpdate = DateTime.Now;
            provincecodes.Insert(_province);
            provincecodes.Commit();

            return RedirectToAction("Index");
        }

        // GET: /Edit/5
        public ActionResult EditProvince(string id)
        {
            //Dropdown list for country
            var country = countrycodes.GetAll();
            ViewBag.Country = country.OrderBy(q => q.name);

            province_view province_view = provinces_view.GetAll().
                Where(c => c.provinceCode == id).FirstOrDefault();

            if (province_view == null)
            {
                return HttpNotFound();
            }
            return View(province_view);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProvince(province_view province_form_page)
        {
            var _province = provincecodes.GetById(province_form_page.provinceCode);

            _province.code = province_form_page.provinceCode;
            _province.name = province_form_page.provinceName;
            _province.countryCode = province_form_page.countryCode;
            _province.lastUpdate = DateTime.Now;
            provincecodes.Update(_province);
            provincecodes.Commit();

            return RedirectToAction("Index");
        }
   }
}

solution/IPMRVPark/IPMRVPark.WebUI/Views/ProvinceView/CreateProvince.cshtml
@model IPMRVPark.Models.province_view

@{
    ViewBag.Title = "Add Province";
    ViewBag.PageTitle = "Add Province";
}
@Html.ActionLink("Home", "Menu", "PrototypeUI")
<span class="glyphicon glyphicon-chevron-right"></span>
Maintenance<span class="glyphicon glyphicon-chevron-right"></span>
@Html.ActionLink("Add Province", "CreateProvince", "ProvinceView")

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
<div class="container-fluid">
    <fieldset>
        <legend></legend>
        <div class="row top-margin">
            <div class="form-group">
                <div class="col-sm-3 col-xs-12 form-top-margin">
                    <label>Province Code :</label>
                </div>
                <div class="col-sm-3 col-xs-12 form-top-margin">
                    <input type="text" class="form-control" id="provinceCode" name="provinceCode" placeholder="enter 2 digits code ..." />
                    @Html.ValidationMessageFor(model => model.provinceCode)
                </div>

                <div class="col-sm-3 col-xs-12 form-top-margin">
                    <label>Province Name :</label>
                </div>
                <div class="col-sm-3 col-xs-12 form-top-margin">
                    <input type="text" class="form-control" id="provinceName" name="provinceName" placeholder="enter province name here ..." />
                    @Html.ValidationMessageFor(model => model.provinceName)
                </div>
            </div>
        </div>
        <div class="row top-margin">
            <div class="form-group">
                <div class="col-sm-3 col-xs-12 form-top-margin">
                    <label>Country :</label>
                </div>
                <div class="col-sm-9 col-xs-12 form-top-margin">
                    @Html.DropDownListFor(model => model.countryCode,
                        new SelectList(ViewBag.Country, "code", "name"),
                        "Select Country",
                        new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.countryCode, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row top-margin">
            <div class="form-group">
                <div class="col-sm-6 col-sm-push-6 col-xs-12 form-top-margin">
                    <button type="submit" class="btn btn-block btn-default">
                        <span class="col-xs-1 glyphicon glyphicon-ok"></span>
                        <span class="col-xs-9">Confirm Province</span>
                    </button>
                </div>
            </div>
        </div>
        <div class="row top-margin">
            <div class="col-sm-6 col-sm-push-6 col-xs-12 form-top-margin" data-toggle="tooltip" title="Go To">
                <a href="@Url.Action("Index", "ProvinceView")" class="btn btn-block btn-default btn-mylink pagination-centered">
                    <span class="glyphicon glyphicon-map-marker"></span>
                    <span>Back to List</span>
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
    </fieldset>
</div>
    
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

solution/IPMRVPark/IPMRVPark.WebUI/Views/ProvinceView/EditProvince.cshtml
@model IPMRVPark.Models.province_view

@{
    ViewBag.Title = "EditProvince";
    ViewBag.PageTitle = "Update Province";
}
@Html.ActionLink("Home", "Menu", "PrototypeUI")
<span class="glyphicon glyphicon-chevron-right"></span>
Maintenance
<span class="glyphicon glyphicon-chevron-right"></span>
@Html.ActionLink("Update Province", "EditProvince", "ProvinceView")

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
<div class="container-fluid">
    <fieldset>
        <legend></legend>
        <div class="row top-margin">
            <div class="form-group">
                <div class="editor-label col-sm-3 col-xs-12 form-top-margin">
                    Province Code :
                </div>
                <div class="editor-field col-sm-3 col-xs-12 form-top-margin">
                    @Html.EditorFor(model => model.provinceCode)
                    @Html.ValidationMessageFor(model => model.provinceCode)
                </div>
                <div class="editor-label col-sm-3 col-xs-12 form-top-margin">
                    Province Name :
                </div>
                <div class="editor-field col-sm-3 col-xs-12 form-top-margin">
                    @Html.EditorFor(model => model.provinceName)
                    @Html.ValidationMessageFor(model => model.provinceName)
                </div>
            </div>
        </div>
        <div class="row top-margin">
            <div class="form-group">
                <div class="editor-label col-sm-3 col-xs-12 form-top-margin">
                    Country :
                </div>
                <div class="editor-field col-sm-3 col-xs-12 form-top-margin">
                    @Html.DropDownListFor(model => model.countryCode,
                        new SelectList(ViewBag.Country, "code", "name"),
                        "Select Country",
                        new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.countryCode, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row top-margin">
            <div class="form-group">
                <div class="editor-label col-sm-5 col-sm-push-1 col-xs-12 form-top-margin">
                    <button type="submit" class="btn btn-block btn-default">
                        <span class="col-xs-1 glyphicon glyphicon-ok"></span>
                        <span class="col-xs-9">Confirm Province Update</span>
                    </button>
                </div>
                <div class="editor-label col-sm-5 col-sm-push-1 colxs-12 form-top-margin">
                    <a href="@Url.Action("Index", "ProvinceView")" class="btn btn-block btn-default btn-mylink pagination-centered">
                        <span class="glyphicon glyphicon-map-marker"></span>
                        <span>Back to List</span>
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div>
            </div>
        </div>
    </fieldset>
</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}